# Site settings
title: "Emporium"
author: "Desamir"
description:
  "A searchable D&D 5e magic item list."
baseurl: "/emporium" # the subpath of your site, e.g. /blog/
url: "https://5ecompendium.github.io" # the base hostname & protocol for your site
source-url: "https://github.com/5ecompendium/emporium/"
permalink: "/:categories/:title"
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "items"

collections:
  items:
    output: true
  tags:
    output: true