# Site settings
title: "Grimoire"
author: "Saph"
description:
  "D&D 5e spell list, sorted by class and level."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
source-url: "https://github.com/ephe/grimoire/"
permalink: "/:categories/:title"

# Build settings
markdown: kramdown
highlighter: pygments

# Site defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "spells"